(defpackage :cl-haml.test
  (:use :cl :fiveam))

(defun parse-haml-line (stream &key package auto-close haml-format escape-html)
  (assert (and package
               (or (eq auto-close t) (eq auto-close nil))
               (or (eql haml-format :xhtml)
                   (eql haml-format :html4)
                   (eql haml-format :html5))
               (or (eq escape-html t)
                   (eq escape-html nil))))
  nil)

(test doctype
  (with-input-from-string (str "!!!")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">")
               (read-haml-line str:package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! Strict")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! Frameset")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Frameset//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! 5")
    (is (equal '("<!DOCTYPE html>")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! 1.1")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml1.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! Basic")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML Basic 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml1.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! Mobile")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//WAPFORUM//DTD XHTML Mobile 1.2//EN\" \"http://www.openmobilealliance.org/tech/DTD/xhtml-mobile12.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!! RDFa")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML+RDFa 1.0//EN\" \"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :xhtml :escape-html nil))))
  (with-input-from-string (str "!!!")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :html4 :escape-html nil))))
  (with-input-from-string (str "!!! Strict")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :html4 :escape-html nil))))
  (with-input-from-string (str "!!! Frameset")
    (is (equal '("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Frameset//EN\" \"http://www.w3.org/TR/html4/frameset.dtd\">")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :html4 :escape-html nil))))
  (with-input-from-string (str "!!!")
    (is (equal '("<!DOCTYPE html>")
               (read-haml-line str :package :cl-haml.test :autoclose t :haml-format :html5 :escape-html nil)))))
